import { Supplier } from "components/common/SupplierCard";

export const name = 1;

export const suppliers: Supplier[] = [
	{
		id: "1",
		name: "TechCorp Manufacturing",
		image: "https://c.animaapp.com/wtIZUsNi/img/random-pp-16.svg",
		country: "China",
		rating: 4.8,
		isBookmarked: false,
		isVIP: true,
		isVerified: true,
		moq: 500,
		location: "Dongguan, Guangdong",
		responseRate: 95,
		tags: [{ label: "Kitchen Appliances" }, { label: "Portable" }, { label: "OEM Available" }],
	},
	{
		id: "2",
		name: "Global Tools Ltd",
		image: "https://c.animaapp.com/wtIZUsNi/img/random-pp-15.svg",
		country: "China",
		rating: 4.8,
		isBookmarked: false,
		isVIP: true,
		isVerified: false,
		moq: 500,
		location: "Guangzhou, Guangdong",
		responseRate: 94,
		tags: [{ label: "Portable" }, { label: "OEM Available" }],
	},
	{
		id: "3",
		name: "Pacific Electronics",
		image: "https://c.animaapp.com/wtIZUsNi/img/random-pp-19.svg",
		country: "China",
		rating: 4.8,
		isBookmarked: false,
		isVIP: false,
		isVerified: true,
		moq: 500,
		location: "Ningbo, Zhejiang",
		responseRate: 90,
		tags: [{ label: "Kitchen Appliances" }, { label: "OEM Available" }],
	},
	{
		id: "4",
		name: "BlendTech Manufacturing",
		image: "https://c.animaapp.com/wtIZUsNi/img/random-pp-18.svg",
		country: "China",
		rating: 4.8,
		isBookmarked: false,
		isVIP: true,
		isVerified: true,
		moq: 500,
		location: "Dongguan, Guangdong",
		responseRate: 87,
		tags: [{ label: "OEM Available" }],
	},
	{
		id: "5",
		name: "Global Tools Ltd",
		image: "https://c.animaapp.com/wtIZUsNi/img/random-pp-15.svg",
		country: "China",
		rating: 4.8,
		isBookmarked: false,
		isVIP: true,
		isVerified: false,
		moq: 500,
		location: "Guangzhou, Guangdong",
		responseRate: 94,
		tags: [{ label: "Portable" }, { label: "OEM Available" }],
	},
	{
		id: "6",
		name: "Global Tools Ltd",
		image: "https://c.animaapp.com/wtIZUsNi/img/random-pp-15.svg",
		country: "China",
		rating: 4.8,
		isBookmarked: false,
		isVIP: true,
		isVerified: false,
		moq: 500,
		location: "Guangzhou, Guangdong",
		responseRate: 94,
		tags: [{ label: "Portable" }, { label: "OEM Available" }],
	},
	{
		id: "7",
		name: "Pacific Electronics",
		image: "https://c.animaapp.com/wtIZUsNi/img/random-pp-19.svg",
		country: "China",
		rating: 4.8,
		isBookmarked: false,
		isVIP: false,
		isVerified: true,
		moq: 500,
		location: "Ningbo, Zhejiang",
		responseRate: 90,
		tags: [{ label: "Kitchen Appliances" }, { label: "OEM Available" }],
	},
];

export const suppliersSearchFilter: Supplier[] = [
	{
		id: "1",
		name: "Global Tools Ltd",
		image: "https://c.animaapp.com/wtIZUsNi/img/random-pp-15.svg",
		country: "China",
		rating: 4.8,
		isBookmarked: false,
		isVIP: true,
		isVerified: false,
		moq: 500,
		location: "Guangzhou, Guangdong",
		responseRate: 94,
		tags: [{ label: "Portable" }, { label: "OEM Available" }],
	},
	{
		id: "2",
		name: "TechCorp Manufacturing",
		image: "https://c.animaapp.com/wtIZUsNi/img/random-pp-16.svg",
		country: "China",
		rating: 4.8,
		isBookmarked: false,
		isVIP: true,
		isVerified: true,
		moq: 500,
		location: "Dongguan, Guangdong",
		responseRate: 95,
		tags: [{ label: "Kitchen Appliances" }, { label: "Portable" }, { label: "OEM Available" }],
	},
	{
		id: "3",
		name: "Global Tools Ltd",
		image: "https://c.animaapp.com/wtIZUsNi/img/random-pp-15.svg",
		country: "China",
		rating: 4.8,
		isBookmarked: false,
		isVIP: true,
		isVerified: false,
		moq: 500,
		location: "Guangzhou, Guangdong",
		responseRate: 94,
		tags: [{ label: "Portable" }, { label: "OEM Available" }],
	},
	{
		id: "4",
		name: "BlendTech Manufacturing",
		image: "https://c.animaapp.com/wtIZUsNi/img/random-pp-18.svg",
		country: "China",
		rating: 4.8,
		isBookmarked: false,
		isVIP: true,
		isVerified: true,
		moq: 500,
		location: "Dongguan, Guangdong",
		responseRate: 87,
		tags: [{ label: "OEM Available" }],
	},
	{
		id: "5",
		name: "Pacific Electronics",
		image: "https://c.animaapp.com/wtIZUsNi/img/random-pp-19.svg",
		country: "China",
		rating: 4.8,
		isBookmarked: false,
		isVIP: false,
		isVerified: true,
		moq: 500,
		location: "Ningbo, Zhejiang",
		responseRate: 90,
		tags: [{ label: "Kitchen Appliances" }, { label: "OEM Available" }],
	},
	{
		id: "6",
		name: "BlendTech Manufacturing",
		image: "https://c.animaapp.com/wtIZUsNi/img/random-pp-18.svg",
		country: "China",
		rating: 4.8,
		isBookmarked: false,
		isVIP: true,
		isVerified: true,
		moq: 500,
		location: "Dongguan, Guangdong",
		responseRate: 87,
		tags: [{ label: "OEM Available" }],
	},
	{
		id: "7",
		name: "Global Tools Ltd",
		image: "https://c.animaapp.com/wtIZUsNi/img/random-pp-15.svg",
		country: "China",
		rating: 4.8,
		isBookmarked: false,
		isVIP: true,
		isVerified: false,
		moq: 500,
		location: "Guangzhou, Guangdong",
		responseRate: 94,
		tags: [{ label: "Portable" }, { label: "OEM Available" }],
	},
	{
		id: "8",
		name: "TechCorp Manufacturing",
		image: "https://c.animaapp.com/wtIZUsNi/img/random-pp-16.svg",
		country: "China",
		rating: 4.8,
		isBookmarked: false,
		isVIP: true,
		isVerified: true,
		moq: 500,
		location: "Dongguan, Guangdong",
		responseRate: 95,
		tags: [{ label: "Kitchen Appliances" }, { label: "Portable" }, { label: "OEM Available" }],
	},
	{
		id: "9",
		name: "Global Tools Ltd",
		image: "https://c.animaapp.com/wtIZUsNi/img/random-pp-15.svg",
		country: "China",
		rating: 4.8,
		isBookmarked: false,
		isVIP: true,
		isVerified: false,
		moq: 500,
		location: "Guangzhou, Guangdong",
		responseRate: 94,
		tags: [{ label: "Portable" }, { label: "OEM Available" }],
	},
	{
		id: "10",
		name: "Pacific Electronics",
		image: "https://c.animaapp.com/wtIZUsNi/img/random-pp-19.svg",
		country: "China",
		rating: 4.8,
		isBookmarked: false,
		isVIP: false,
		isVerified: true,
		moq: 500,
		location: "Ningbo, Zhejiang",
		responseRate: 90,
		tags: [{ label: "Kitchen Appliances" }, { label: "OEM Available" }],
	},
];

export const RfqCenterInbox: Supplier[] = [
	{
		id: "1",
		name: "Global Tools Ltd",
		image: "https://c.animaapp.com/wtIZUsNi/img/random-pp-15.svg",
		country: "China",
		rating: 4.8,
		isBookmarked: false,
		isVIP: true,
		isVerified: true,
		moq: 500,
		location: "Guangzhou, Guangdong",
		responseRate: 94,
		tags: [{ label: "Portable" }, { label: "OEM Available" }],
	},
	{
		id: "2",
		name: "BlendTech Manufacturing",
		image: "https://c.animaapp.com/wtIZUsNi/img/random-pp-18.svg",
		country: "Germany",
		rating: 4.8,
		isBookmarked: false,
		isVIP: true,
		isVerified: true,
		moq: 500,
		location: "Guangzhou, Guangdong",
		responseRate: 87,
		tags: [{ label: "Portable" }, { label: "OEM Available" }],
	},
	{
		id: "3",
		name: "Pacific Electronics",
		image: "https://c.animaapp.com/wtIZUsNi/img/random-pp-19.svg",
		country: "France",
		rating: 4.8,
		isBookmarked: false,
		isVIP: true,
		isVerified: true,
		moq: 500,
		location: "Guangzhou, Guangdong",
		responseRate: 90,
		tags: [{ label: "Portable" }, { label: "OEM Available" }],
	},
	{
		id: "4",
		name: "Global Tools Ltd",
		image: "https://c.animaapp.com/wtIZUsNi/img/random-pp-15.svg",
		country: "Newyork",
		rating: 4.8,
		isBookmarked: false,
		isVIP: true,
		isVerified: true,
		moq: 500,
		location: "Guangzhou, Guangdong",
		responseRate: 94,
		tags: [{ label: "Portable" }, { label: "OEM Available" }],
	},
	{
		id: "5",
		name: "TechCorp Manufacturing",
		image: "https://c.animaapp.com/wtIZUsNi/img/random-pp-16.svg",
		country: "United States",
		rating: 4.8,
		isBookmarked: false,
		isVIP: true,
		isVerified: true,
		moq: 500,
		location: "Guangzhou, Guangdong",
		responseRate: 95,
		tags: [{ label: "Portable" }, { label: "OEM Available" }],
	},
	{
		id: "6",
		name: "Pacific Electronics",
		image: "https://c.animaapp.com/wtIZUsNi/img/random-pp-19.svg",
		country: "Japan",
		rating: 4.8,
		isBookmarked: false,
		isVIP: true,
		isVerified: true,
		moq: 500,
		location: "Guangzhou, Guangdong",
		responseRate: 90,
		tags: [{ label: "Portable" }, { label: "OEM Available" }],
	},
	{
		id: "7",
		name: "Global Tools Ltd",
		image: "https://c.animaapp.com/wtIZUsNi/img/random-pp-15.svg",
		country: "China",
		rating: 4.8,
		isBookmarked: false,
		isVIP: true,
		isVerified: false,
		moq: 500,
		location: "Guangzhou, Guangdong",
		responseRate: 94,
		tags: [{ label: "Portable" }, { label: "OEM Available" }],
	},
	{
		id: "8",
		name: "BlendTech Manufacturing",
		image: "https://c.animaapp.com/wtIZUsNi/img/random-pp-18.svg",
		country: "China",
		rating: 4.8,
		isBookmarked: false,
		isVIP: true,
		isVerified: true,
		moq: 500,
		location: "Guangzhou, Guangdong",
		responseRate: 87,
		tags: [{ label: "Portable" }, { label: "OEM Available" }],
	},
	{
		id: "9",
		name: "Global Tools Ltd",
		image: "https://c.animaapp.com/wtIZUsNi/img/random-pp-15.svg",
		country: "China",
		rating: 4.8,
		isBookmarked: false,
		isVIP: true,
		isVerified: false,
		moq: 500,
		location: "Guangzhou, Guangdong",
		responseRate: 94,
		tags: [{ label: "Portable" }, { label: "OEM Available" }],
	},
	{
		id: "10",
		name: "TechCorp Manufacturing",
		image: "https://c.animaapp.com/wtIZUsNi/img/random-pp-16.svg",
		country: "China",
		rating: 4.8,
		isBookmarked: false,
		isVIP: true,
		isVerified: true,
		moq: 500,
		location: "Guangzhou, Guangdong",
		responseRate: 95,
		tags: [{ label: "Portable" }, { label: "OEM Available" }],
	},
];
export const RfqCenterSent: Supplier[] = [
	{
		id: "1",
		name: "Custom Injection Molded Parts",
		image: "https://c.animaapp.com/wtIZUsNi/img/random-pp-15.svg",
		country: "China",
		rating: 4.8,
		isBookmarked: false,
		isVIP: true,
		isVerified: true,
		moq: 500,
		location: "Guangzhou, Guangdong",
		responseRate: 94,
		tags: [{ label: "Plastic" }, { label: "Food-grade" }],
	},
	{
		id: "2",
		name: "Stainless Steel Fasteners",
		image: "https://c.animaapp.com/wtIZUsNi/img/random-pp-18.svg",
		country: "Germany",
		rating: 4.8,
		isBookmarked: false,
		isVIP: true,
		isVerified: true,
		moq: 500,
		location: "Guangzhou, Guangdong",
		responseRate: 87,
		tags: [{ label: "Fasteners" }, { label: "Stainless" }, { label: "Hardware" }],
	},
	{
		id: "3",
		name: "Automotive Rubber Seals",
		image: "https://c.animaapp.com/wtIZUsNi/img/random-pp-19.svg",
		country: "France",
		rating: 4.8,
		isBookmarked: false,
		isVIP: true,
		isVerified: true,
		moq: 500,
		location: "Guangzhou, Guangdong",
		responseRate: 90,
		tags: [{ label: "Automotive" }, { label: "Rubber" }, { label: "Seals" }],
	},
	{
		id: "4",
		name: "Custom Injection Molded Parts",
		image: "https://c.animaapp.com/wtIZUsNi/img/random-pp-15.svg",
		country: "Newyork",
		rating: 4.8,
		isBookmarked: false,
		isVIP: true,
		isVerified: true,
		moq: 500,
		location: "Guangzhou, Guangdong",
		responseRate: 94,
		tags: [{ label: "Plastic" }, { label: "Food-grade" }],
	},
	{
		id: "5",
		name: "Custom Injection Molded Parts",
		image: "https://c.animaapp.com/wtIZUsNi/img/random-pp-16.svg",
		country: "United States",
		rating: 4.8,
		isBookmarked: false,
		isVIP: true,
		isVerified: true,
		moq: 500,
		location: "Guangzhou, Guangdong",
		responseRate: 95,
		tags: [{ label: "Plastic" }, { label: "Food-grade" }],
	},
	{
		id: "6",
		name: "Custom Injection Molded Parts",
		image: "https://c.animaapp.com/wtIZUsNi/img/random-pp-19.svg",
		country: "Japan",
		rating: 4.8,
		isBookmarked: false,
		isVIP: true,
		isVerified: true,
		moq: 500,
		location: "Guangzhou, Guangdong",
		responseRate: 90,
		tags: [{ label: "Plastic" }, { label: "Food-grade" }],
	},
	{
		id: "7",
		name: "Custom Injection Molded Parts",
		image: "https://c.animaapp.com/wtIZUsNi/img/random-pp-15.svg",
		country: "China",
		rating: 4.8,
		isBookmarked: false,
		isVIP: true,
		isVerified: false,
		moq: 500,
		location: "Guangzhou, Guangdong",
		responseRate: 94,
		tags: [{ label: "Portable" }, { label: "OEM Available" }],
	},
	{
		id: "8",
		name: "Stainless Steel Fasteners",
		image: "https://c.animaapp.com/wtIZUsNi/img/random-pp-18.svg",
		country: "China",
		rating: 4.8,
		isBookmarked: false,
		isVIP: true,
		isVerified: true,
		moq: 500,
		location: "Guangzhou, Guangdong",
		responseRate: 87,
		tags: [{ label: "Portable" }, { label: "OEM Available" }],
	},
	{
		id: "9",
		name: "Automotive Rubber Seals",
		image: "https://c.animaapp.com/wtIZUsNi/img/random-pp-15.svg",
		country: "China",
		rating: 4.8,
		isBookmarked: false,
		isVIP: true,
		isVerified: false,
		moq: 500,
		location: "Guangzhou, Guangdong",
		responseRate: 94,
		tags: [{ label: "Portable" }, { label: "OEM Available" }],
	},
	{
		id: "10",
		name: "TechCorp Manufacturing",
		image: "https://c.animaapp.com/wtIZUsNi/img/random-pp-16.svg",
		country: "China",
		rating: 4.8,
		isBookmarked: false,
		isVIP: true,
		isVerified: true,
		moq: 500,
		location: "Guangzhou, Guangdong",
		responseRate: 95,
		tags: [{ label: "Portable" }, { label: "OEM Available" }],
	},
];

export const countryOptions = [
	{ value: "AF", label: "Afghanistan" },
	{ value: "AR", label: "Argentina" },
	{ value: "AU", label: "Australia" },
	{ value: "BD", label: "Bangladesh" },
	{ value: "BR", label: "Brazil" },
	{ value: "CA", label: "Canada" },
	{ value: "CN", label: "China" },
	{ value: "DE", label: "Germany" },
	{ value: "EG", label: "Egypt" },
	{ value: "FR", label: "France" },
	{ value: "IN", label: "India" },
	{ value: "ID", label: "Indonesia" },
	{ value: "IT", label: "Italy" },
	{ value: "JP", label: "Japan" },
	{ value: "MX", label: "Mexico" },
	{ value: "NG", label: "Nigeria" },
	{ value: "PK", label: "Pakistan" },
	{ value: "RU", label: "Russia" },
	{ value: "SA", label: "Saudi Arabia" },
	{ value: "ZA", label: "South Africa" },
	{ value: "KR", label: "South Korea" },
	{ value: "ES", label: "Spain" },
	{ value: "LK", label: "Sri Lanka" },
	{ value: "TH", label: "Thailand" },
	{ value: "TR", label: "Turkey" },
	{ value: "UA", label: "Ukraine" },
	{ value: "AE", label: "United Arab Emirates" },
	{ value: "GB", label: "United Kingdom" },
	{ value: "US", label: "United States" },
	{ value: "VN", label: "Vietnam" },
];
