import { Supplier } from "components/common/SupplierCard";

export const name = 1;

export const suppliers: Supplier[] = [
	{
		id: "1",
		name: "Global Tools Ltd",
		image: "https://c.animaapp.com/wtIZUsNi/img/random-pp-15.svg",
		country: "China",
		rating: 4.8,
		isBookmarked: false,
		isVIP: true,
		isVerified: false,
		moq: 500,
		location: "Guangzhou, Guangdong",
		responseRate: 94,
		tags: [{ label: "Portable" }, { label: "OEM Available" }],
	},
	{
		id: "2",
		name: "TechCorp Manufacturing",
		image: "https://c.animaapp.com/wtIZUsNi/img/random-pp-16.svg",
		country: "China",
		rating: 4.8,
		isBookmarked: false,
		isVIP: true,
		isVerified: true,
		moq: 500,
		location: "Dongguan, Guangdong",
		responseRate: 95,
		tags: [{ label: "Kitchen Appliances" }, { label: "Portable" }, { label: "OEM Available" }],
	},
	{
		id: "1",
		name: "Global Tools Ltd",
		image: "https://c.animaapp.com/wtIZUsNi/img/random-pp-15.svg",
		country: "China",
		rating: 4.8,
		isBookmarked: false,
		isVIP: true,
		isVerified: false,
		moq: 500,
		location: "Guangzhou, Guangdong",
		responseRate: 94,
		tags: [{ label: "Portable" }, { label: "OEM Available" }],
	},
	{
		id: "3",
		name: "Pacific Electronics",
		image: "https://c.animaapp.com/wtIZUsNi/img/random-pp-19.svg",
		country: "China",
		rating: 4.8,
		isBookmarked: false,
		isVIP: false,
		isVerified: true,
		moq: 500,
		location: "Ningbo, Zhejiang",
		responseRate: 90,
		tags: [{ label: "Kitchen Appliances" }, { label: "OEM Available" }],
	},
	{
		id: "1",
		name: "Global Tools Ltd",
		image: "https://c.animaapp.com/wtIZUsNi/img/random-pp-15.svg",
		country: "China",
		rating: 4.8,
		isBookmarked: false,
		isVIP: true,
		isVerified: false,
		moq: 500,
		location: "Guangzhou, Guangdong",
		responseRate: 94,
		tags: [{ label: "Portable" }, { label: "OEM Available" }],
	},
	{
		id: "4",
		name: "BlendTech Manufacturing",
		image: "https://c.animaapp.com/wtIZUsNi/img/random-pp-18.svg",
		country: "China",
		rating: 4.8,
		isBookmarked: false,
		isVIP: true,
		isVerified: true,
		moq: 500,
		location: "Dongguan, Guangdong",
		responseRate: 87,
		tags: [{ label: "OEM Available" }],
	},
	{
		id: "3",
		name: "Pacific Electronics",
		image: "https://c.animaapp.com/wtIZUsNi/img/random-pp-19.svg",
		country: "China",
		rating: 4.8,
		isBookmarked: false,
		isVIP: false,
		isVerified: true,
		moq: 500,
		location: "Ningbo, Zhejiang",
		responseRate: 90,
		tags: [{ label: "Kitchen Appliances" }, { label: "OEM Available" }],
	},
];
